version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345678Aa.
      - POSTGRES_DB=gecekodu
    ports:
      - "5433:5432"  # Dışarıya açılan port
    networks:
      - nginx-network

  gecekodu-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:8080"  # Uygulamanın dışa açılan portu
    restart: unless-stopped
    environment:
      - DB_SOURCE=postgresql://root:12345678Aa.@postgres:5432/gecekodu?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432"]
    command: ["dotnet", "WebApiLayer.dll", "--environment=Development"]
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
